name: website build test

on: [pull_request]

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Build
        working-directory: .
        run: npm run build
